// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MyApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200504094708_CreateData")]
    partial class CreateData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MyApp.Models.Entities.Montain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("PrefectureId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PrefectureId");

                    b.ToTable("Montains");
                });

            modelBuilder.Entity("MyApp.Models.Entities.Prefecture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Prefectures");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "北海道",
                            Order = 1,
                            ShortName = "北海道"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "青森県",
                            Order = 2,
                            ShortName = "青森"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "岩手県",
                            Order = 3,
                            ShortName = "岩手"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "宮城県",
                            Order = 4,
                            ShortName = "宮城"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "秋田県",
                            Order = 5,
                            ShortName = "秋田"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "山形県",
                            Order = 6,
                            ShortName = "山形"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "福島県",
                            Order = 7,
                            ShortName = "福島"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "茨城県",
                            Order = 8,
                            ShortName = "茨城"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "栃木県",
                            Order = 9,
                            ShortName = "栃木"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "群馬県",
                            Order = 10,
                            ShortName = "群馬"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "埼玉県",
                            Order = 11,
                            ShortName = "埼玉"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "千葉県",
                            Order = 12,
                            ShortName = "千葉"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "東京都",
                            Order = 13,
                            ShortName = "東京"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "神奈川県",
                            Order = 14,
                            ShortName = "神奈川"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "新潟県",
                            Order = 15,
                            ShortName = "新潟"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "富山県",
                            Order = 16,
                            ShortName = "富山"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "石川県",
                            Order = 17,
                            ShortName = "石川"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "福井県",
                            Order = 18,
                            ShortName = "福井"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "山梨県",
                            Order = 19,
                            ShortName = "山梨"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "長野県",
                            Order = 20,
                            ShortName = "長野"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "岐阜県",
                            Order = 21,
                            ShortName = "岐阜"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "静岡県",
                            Order = 22,
                            ShortName = "静岡"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "愛知県",
                            Order = 23,
                            ShortName = "愛知"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "三重県",
                            Order = 24,
                            ShortName = "三重"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "滋賀県",
                            Order = 25,
                            ShortName = "滋賀"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "京都府",
                            Order = 26,
                            ShortName = "京都"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "大阪府",
                            Order = 27,
                            ShortName = "大阪"
                        },
                        new
                        {
                            Id = 28L,
                            Name = "兵庫県",
                            Order = 28,
                            ShortName = "兵庫"
                        },
                        new
                        {
                            Id = 29L,
                            Name = "奈良県",
                            Order = 29,
                            ShortName = "奈良"
                        },
                        new
                        {
                            Id = 30L,
                            Name = "和歌山県",
                            Order = 30,
                            ShortName = "和歌山"
                        },
                        new
                        {
                            Id = 31L,
                            Name = "鳥取県",
                            Order = 31,
                            ShortName = "鳥取"
                        },
                        new
                        {
                            Id = 32L,
                            Name = "島根県",
                            Order = 32,
                            ShortName = "島根"
                        },
                        new
                        {
                            Id = 33L,
                            Name = "岡山県",
                            Order = 33,
                            ShortName = "岡山"
                        },
                        new
                        {
                            Id = 34L,
                            Name = "広島県",
                            Order = 34,
                            ShortName = "広島"
                        },
                        new
                        {
                            Id = 35L,
                            Name = "山口県",
                            Order = 35,
                            ShortName = "山口"
                        },
                        new
                        {
                            Id = 36L,
                            Name = "徳島県",
                            Order = 36,
                            ShortName = "徳島"
                        },
                        new
                        {
                            Id = 37L,
                            Name = "香川県",
                            Order = 37,
                            ShortName = "香川"
                        },
                        new
                        {
                            Id = 38L,
                            Name = "愛媛県",
                            Order = 38,
                            ShortName = "愛媛"
                        },
                        new
                        {
                            Id = 39L,
                            Name = "高知県",
                            Order = 39,
                            ShortName = "高知"
                        },
                        new
                        {
                            Id = 40L,
                            Name = "福岡県",
                            Order = 40,
                            ShortName = "福岡"
                        },
                        new
                        {
                            Id = 41L,
                            Name = "佐賀県",
                            Order = 41,
                            ShortName = "佐賀"
                        },
                        new
                        {
                            Id = 42L,
                            Name = "長崎県",
                            Order = 42,
                            ShortName = "長崎"
                        },
                        new
                        {
                            Id = 43L,
                            Name = "熊本県",
                            Order = 43,
                            ShortName = "熊本"
                        },
                        new
                        {
                            Id = 44L,
                            Name = "大分県",
                            Order = 44,
                            ShortName = "大分"
                        },
                        new
                        {
                            Id = 45L,
                            Name = "宮崎県",
                            Order = 45,
                            ShortName = "宮崎"
                        },
                        new
                        {
                            Id = 46L,
                            Name = "鹿児島県",
                            Order = 46,
                            ShortName = "鹿児島"
                        },
                        new
                        {
                            Id = 47L,
                            Name = "沖縄県",
                            Order = 47,
                            ShortName = "沖縄"
                        });
                });

            modelBuilder.Entity("MyApp.Models.Entities.Montain", b =>
                {
                    b.HasOne("MyApp.Models.Entities.Prefecture", "Prefecture")
                        .WithMany()
                        .HasForeignKey("PrefectureId");
                });
#pragma warning restore 612, 618
        }
    }
}
